
name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.1'

      - name: Build site
        run: go run buildSite.go

      - name: Archive site artifacts
        uses: actions/upload-artifact@v2
        with:
          name: notes
          path: deploy/
