name: build-and-deploy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.1"

      - name: Build site
        run: go run buildSite.go

      - name: Archive site artifacts
        uses: actions/upload-artifact@v2
        with:
          name: notes
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: notes
          path: deploy

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user

      - name: Deploy to S3
        run: |
          aws s3 sync ./deploy s3://your-bucket-name --delete
